/* Arithmetic Operators */

DATA ARITHMETIC_OPERATION;
INPUT @1 COLOUR_1 @7 COLOUR_2;
ADDITION = COLOUR_1 + COLOUR_2;
SUBTRATION = COLOUR_2 - COLOUR_1;
MULTIPLICATION = COLOUR_1 * COLOUR_2;
DIVISION = COLOUR_1 / COLOUR_2;
EXPOTENSIAL = COLOUR_1**COLOUR_2;
DATALINES;
33.13 56.78
35.22 58.23
;
RUN;
PROC PRINT DATA = ARITHMETIC_OPERATION;
RUN;



/* Logical Operators */

DATA LOGICAL_OPERATION;
INPUT @1 COLOUR_1 @7 COLOUR_2;
AND_OPERATOR = (COLOUR_1 > 5 & COLOUR_2 < 10);
OR_OPERATOR = (COLOUR_1 > 5 | COLOUR_2 < 10);
NOT_OPERATOR = ~(COLOUR_1 < 10);
DATALINES;
15 20
20 30
;
PROC PRINT DATA = LOGICAL_OPERATION;
RUN;




/* Comparison Operators */

DATA COMPARISON_OPERATION;
INPUT @1 COLOUR_1 @7 COLOUR_2;
EQUAL = (COLOUR_1 = 33);
NOT_EQUAL = (COLOUR_1 ^= 221);
GRATER_EQUAL = (COLOUR_1 => 555); 
/* Here grater operator hold in COLOUR_2 */
LESS_EQUAL = (COLOUR_1 <= 10); 
/* Here less operator hold in COLOUR_2 */
IN = COLOUR_1 IN(22.2,33.56);
DATALINES;
22.2 44.2
33.54 11.66
;
RUN;
PROC PRINT DATA = COMPARISON_OPERATION;
RUN;


/* Minimum/Maximum Operators */

DATA MIN_MAX_OPERATOER;
INPUT @1 COLOUR_1 @7 COLOUR_2 @12 COLOUR_3;
MIN_COUNT = MIN(COLOUR_1, COLOUR_2, COLOUR_3);
MAX_COUNT = MAX(COLOUR_1, COLOUR_2, COLOUR_3);
DATALINES;
22.4 44.3 55.2
33.66 66.33 99.11
;
RUN;
PROC PRINT DATA = MIN_MAX_OPERATOER;
RUN;

